@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

skinparam class {
BackgroundColor LightYellow
}

entity box {
*transaction_id : String
* branch_label : String
*output_index : u16
--
*asset_class : String
security_root : String
metadata : String
consuming_transaction_id : String
consuming_branch_label : String
input_index : u16
}

entity transaction {
*transaction_id : String
*branch_label : String
--
}

transaction ||--|{ box : inputs
transaction ||--|{ box : outputs
@enduml
