@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

skinparam class {
  BackgroundColor LightYellow
}

entity wallet {
  *id : byte[32]
  --
  *name : String
  description : String
  *seed: base58 encoded bytes
}

entity "identity_evidence" as identity {
  *id : UUID <<generated>>
  --
  *evidence_type
  ...
}

entity account  {
  *account_id : int32
  --
  description: String
  address_index: int32
}

entity account_alias {
  * alias : String
}

entity asset_class  {
    * account_id : int32
    * asset_class_id : String
}

entity "address" as addr  {
  *address_index: int32
  --
  *address_id : base58
  *"public_key" : base58
  *"private_key" : base58
  description : String
}

entity "foreign_address" as foreign  {
  *address_index: int32
  --
  *addressId : base58
  *"public_key" : base58
  *wallet: UUID
  description : String
}

entity "proposition" as prop  {
  *"proposition_hash" : base58
}

entity "incomplete_proof" as proof  {
  *"proposition_hash" : base58
}

foreign }o..|{ addr
wallet ||.o{ identity
wallet ||..o{ account
wallet ||..o{account_alias
account||.o{account_alias
account |o...o{ addr : "Collection of\nsingle use\naddresses"
account ||.o{ asset_class
asset_class |o..|| addr
addr ||..o| prop
proof |o.||addr
foreign ||..o| prop
foreign ||..o| proof
@enduml
