@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

skinparam class {
  BackgroundColor LightYellow
}

entity wallet {
  *id : byte[32]
  --
  *name : String
  description : String
  wallet_type: String
  *seed: base58 encoded bytes
}

entity "identity_evidence" as identity {
  *id : UUID <<generated>>
  --
  *evidence_type
  ...
}

entity foreign_wallet {
  *id: byte[32]
  --
  *uri: String
  description: String
  * signature_algorithm: String
  * verification_key: String
}

entity credential_set {
  *credential_set_id
}

entity application {
  *id : UUID
  --
  *application_name
}

entity account  {
  *account_id : int32
  --
  description: String
  address_index: int32
}

entity account_alias {
  * alias : String
}

entity asset_class  {
    * asset_class_id : String
}

entity asset_quantity {
    ---
    quantity : Int128
}

entity "address" as addr  {
  *address_index: int32
  --
  *address_id : base58
  *"public_key" : base58
  *"private_key" : base58
  *signature_algorithm : String
  description : String
}

entity box {
  sequence_number : u16
  --
  asset_class : String
  quantity : Int128
  status : String ("settled"|"pending"|"spent")
}

entity "foreign_address" as foreign  {
  *address_index: int32
  --
  *addressId : base58
  *"public_key" : base58
  description : String
}

entity "proposition" as prop  {
  *"proposition_hash" : base58
  --
  *proposition_json : String
}

entity "incomplete_proof" as proof  {
  *"proposition_hash" : base58
}

foreign }o..|{ account
wallet ||.o{ identity
wallet ||.o{ application
application ||..o{ account
account_alias}o..||application
(wallet, application) . credential_set
wallet ||..o{ foreign_wallet
credential_set . (foreign_wallet, wallet)
foreign_wallet ||..o{ foreign
account||.o{account_alias
account |o...o{ addr : "Collection of\nsingle use\naddresses"
asset_class }o.|| account
asset_class ||..o{ asset_quantity
asset_quantity }|..|| addr
addr |o..o| prop
addr ||.o{ box
proof |o.||addr
foreign |o..o| prop
foreign ||..o| proof
credential_set -[hidden] foreign
@enduml
