@startuml
hide empty members
page 1x3
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

Interface BifrostTetraClient <<interface>>

Interface MessageDigester <<interface>>

interface Result<SuccessType, FaulureType> <<interface>> {
--
isSuccess
}

class Failure<SuccessType, FaulureType> implements Result

class Success<SuccessType, FaulureType> implements Result

Interface IndexedObject {
  getPath
}

interface ParticipantEntity extends IndexedObject

interface ContractAccount extends IndexedObject

interface Address extends IndexedObject

interface SupplyPolicy

interface Proof

interface Proposition

interface Provider

interface StagedFuture {
  settled : Future
  submission : Future
}

class Box

class AddressableBox
AddressableBox --> "1 " Box
AddressableBox --> " 1" Address

class MessageDigesterFactory <<utility>>  {
--
blake2b160Digester
blake2b256Digester
blake2b384Digester
...
}

MessageDigesterFactory .> MessageDigester : creates
MessageDigester <|.. Blake2b160Digester
MessageDigester <|... Blake2b256Digester
MessageDigester <|.... Blake2b384Digester
MessageDigester <|..... Blake2b512Digester
MessageDigester <|...... Blake2s128Digester
MessageDigester <|....... Blake2s160Digester
MessageDigester <|........ Blake2s224Digester
MessageDigester <|....... Blake2s256Digester
MessageDigester <|....... Blake3_256Digester
MessageDigester <|...... DSTU7564_256Digester
MessageDigester <|..... DSTU7564_384Digester
MessageDigester <|... DSTU7564_512Digester
MessageDigester <|.. RIPEMD_128Digester
MessageDigester <|.... RIPEMD_160Digester
MessageDigester <|..... RIPEMD_256Digester
MessageDigester <|...... RIPEMD_320Digester
MessageDigester <|....... SHA1Digester
MessageDigester <|....... SHA2_224Digester
MessageDigester <|........ SHA2_256Digester
MessageDigester <|....... SHA2_384Digester
MessageDigester <|...... SHA2_512Digester
MessageDigester <|..... SHA3_224Digester
MessageDigester <|.... SHA3_256Digester
MessageDigester <|... SHA3_512Digester
MessageDigester <|.. WhirlpoolDigester

BifrostTetraClient <|.. BifrostClient

Class03 *-- Class04
Class05 o-- Class06
@enduml