@startuml
skinparam sequence {
  LifeLineBackgroundColor #FFBBBB
}

autonumber
autoactivate on
actor user
participant "EZ_API:client" as client
participant "LevelDbWallet:wallet" as wallet
database levelDB
participant "Y:a1" as a1
title a1 = wallet.createAccount(name = "A1")
user -> wallet : createAccount("A1")
  wallet -> wallet : nextXIndex(0)
    wallet -> levelDB : getXRecord(0)
    return

    wallet -> levelDB : updateXRecord(0)
    return
  return indexValue

  wallet -> levelDB : writeYrecord(0,indexValue)
  return <nothing>

  create a1
  wallet -> a1 : constructor
  return a1
return a1
@enduml