@startuml
skinparam sequence {
  LifeLineBackgroundColor #FFBBBB
}
title Open Wallet
autonumber
autoactivate on
actor user
participant "EZ_API:client" as client
participant "LevelDbWallet:wallet" as wallet
database levelDB
participant "__Provider:mainnet__" as mainnet
user ->client: open(mainnet)
  client -> WalletFactory: open(mainnet)
    WalletFactory -> mainnet: getNetworkId
    return networkId

    create wallet
    WalletFactory -> wallet : constructor(networkId)
      create levelDB
      wallet -> levelDB : constructor
      return levelDB

      wallet -> levelDB : getCredentialSet
      return credentialSet
    return wallet

  return wallet
return
@enduml